// Standaard woordenlijst: [frans, nederlands]
// Aan te passen in de app via "Woordenlijst aanpassen" (wordt in localStorage bewaard).
const DEFAULT_WORDS = [
  ["le chien", "de hond"],
  ["le chat", "de kat"],
  ["la maison", "het huis"],
  ["l'école", "de school"],
  ["le livre", "het boek"],
  ["la voiture", "de auto"],
  ["le vélo", "de fiets"],
  ["la pomme", "de appel"],
  ["le pain", "het brood"],
  ["le fromage", "de kaas"],
  ["l'eau", "het water"],
  ["le lait", "de melk"],
  ["la table", "de tafel"],
  ["la chaise", "de stoel"],
  ["la fenêtre", "het raam"],
  ["la porte", "de deur"],
  ["le jardin", "de tuin"],
  ["la rue", "de straat"],
  ["la ville", "de stad"],
  ["le pays", "het land"],
  ["le frère", "de broer"],
  ["la sœur", "de zus"],
  ["les parents", "de ouders"],
  ["l'ami", "de vriend"],
  ["le temps", "het weer / de tijd"],
  ["le soleil", "de zon"],
  ["la pluie", "de regen"],
  ["la neige", "de sneeuw"],
  ["aujourd'hui", "vandaag"],
  ["demain", "morgen"],
  ["hier", "gisteren"],
  ["toujours", "altijd"],
  ["jamais", "nooit"],
  ["souvent", "vaak"],
  ["manger", "eten"],
  ["boire", "drinken"],
  ["dormir", "slapen"],
  ["parler", "praten"],
  ["écouter", "luisteren"],
  ["regarder", "kijken"],
  ["travailler", "werken"],
  ["jouer", "spelen"],
  ["acheter", "kopen"],
  ["vendre", "verkopen"],
  ["ouvrir", "openen"],
  ["fermer", "sluiten"],
  ["grand", "groot"],
  ["petit", "klein"],
  ["beau", "mooi"],
  ["nouveau", "nieuw"],
  ["vieux", "oud"],
  ["facile", "makkelijk"],
  ["difficile", "moeilijk"],
  ["heureux", "gelukkig"],
  ["triste", "verdrietig"],
  ["vite", "snel"],
  ["lentement", "langzaam"],
  ["beaucoup", "veel"],
  ["peu", "weinig"],
  ["ensemble", "samen"],
];
